### ISSUE TITLE
Depends on deprecated cookbook python

### ISSUE THREAD

**Issue by robdefeo** [poise/supervisor#102]
When using poise-python cookbook and setting up a venv with python 3 the installation of supervisor fails.

```
==> default: [2016-01-04T22:12:28+00:00] ERROR: python_pip[supervisor] (supervisor::default line 29) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of pip install  --upgrade supervisor ----
==> default: STDOUT: Collecting supervisor
==> default:   Using cached supervisor-3.2.0.tar.gz
==> default:     Complete output from command python setup.py egg_info:
==> default:     Supervisor requires Python 2.4 or later but does not work on any version of Python 3.  You are using version 3.4.3 (default, Oct 14 2015, 20:28:29)
==> default:     [GCC 4.8.4].  Please install using a supported version.
==> default:     
==> default:     ----------------------------------------
==> default: STDERR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k57arkip/supervisor
```

It appears to be depending on the previous cookbook for python and supervisor cookbook offers no way to install from source with the master branch now supporting python 3

**Comment by coderanger** [comment]
Working on it, there is already a new poise-supervisor cookbook in progress on github.

**Comment by keen99** [comment]
so.... this cookbook will be replaced with another instead of updating it?  confused.

**Comment by coderanger** [comment]
@keen99 This cookbook will turn into a compat wrapper just like the old `monit` cookbook I just took over.

**Comment by bcg62** [comment]
+1 breaking with chef 13

**Comment by gmccue** [comment]
Also seeing this issue with Chef 13. Working on a fix right now, and I'll submit a PR when it's ready. @coderanger has this cookbook been superseded by another?

**Comment by shayangz** [comment]
Any update on this transition? [poise-supervisor](https://github.com/poise/poise-supervisor) hasn't been touched in years and this cookbook is broken under chef 13.

**Comment by coderanger** [comment]
Same place it's been, when I get to it.

**Comment by gmccue** [comment]
In the end, I used `systemd` to monitor processes instead of `supervisor`.
