### ISSUE TITLE
Service template permissions (mode)

### ISSUE THREAD

**Issue by jwmarshall** [poise/supervisor#103]
Would you be receptive to a PR that exposes the service template file permissions (mode) to the resource provider? I have some secrets in the files that I do not want world readable. Sure I could just run a resource immediately after to change the permissions but it would be less typing to set the mode per supervisor_service resource.

https://github.com/poise/supervisor/blob/master/providers/service.rb#L97

Thanks for the great cookbook BTW. I've used it many many times!

**Comment by coderanger** [comment]
No, this cookbook is about to be deprecated and turned into a wrapper. The new code sets files to 600 for this reason :)

**Comment by coderanger** [comment]
No, this cookbook is about to be deprecated and turned into a wrapper. The new code sets files to 600 for this reason :)

**Comment by coderanger** [comment]
No, this cookbook is about to be deprecated and turned into a wrapper. The new code sets files to 600 for this reason :)

**Comment by jwmarshall** [comment]
Fair enough! Thanks for all your work.
