### ISSUE TITLE
How to set attributes

### ISSUE THREAD

**Issue by badsector3** [poise/supervisor#106]
Hi. I have a question regarding the cookbook.
I try to configure supervisor config file and I need to pass following attributes:
[program:name]
command=
directory=
autostart=
user=
stdout_logfile=
stderr_logfile=

I would like to use chef role for that and I have as following:
```ruby
default_attributes(
    :supervisor_service => {
        "daemon_options" => {
            "service_name" => "kafka-broker-4555",
            "autostart"    => true,
            "user"         => "kafka"
        }
    }
)
```
It doesn't work so the above is incorrect.

**Comment by coderanger** [comment]
This cookbook is deprecated and no longer supported. Do not use it.
