### ISSUE TITLE
Default value for `autorestart` is a symbol when it should be a string

### ISSUE THREAD

**Issue by sethvargo** [poise/supervisor#44]
Migrated from [COOK-2777](https://tickets.opscode.com/browse/COOK-2777)

The default value of `autorestart` for the supervisor_service provider is a symbol `:unexpected`. The template uses incorrect logic and ends up rendering `true` instead of what I would assume to be `unexpected`.

**Comment by nollieheel** [comment]
Has this issue ever been resolved? It doesn't look like it. The resource file `service.rb` still makes `autorestart` default to `:unexpected`, but the the template `program.conf.erb` itself only checks for `String` type before defaulting to `true`.
