### ISSUE TITLE
Template doesn't escape percent sign

### ISSUE THREAD

**Issue by preichenberger** [poise/supervisor#60]
If you give a hash with a percent character in the key or value, the conf file will give a read error.

**Comment by alexbartsch** [comment]
Same here. I'm experiencing problems with using a dynamic program_name for multiple processes.

`program_name "%(program_name)s %(process_num)s"`
http://supervisord.org/configuration.html#program-x-section-settings

Error message is 
> Invalid name: '%(program_name)s %(process_num)s'
